import type { Metadata } from 'next';
import { Inter, Poltawski_Nowy, Faculty_Glyphic } from 'next/font/google';
import './globals.css';
import SessionClientProvider from './SessionClientProvider';
import ProtectedPages from './ProtectedPages';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const poltawskiNowy = Poltawski_Nowy({
  variable: '--font-poltwaski-nowy',
  subsets: ['latin'],
});

const facultyGlyphic = Faculty_Glyphic({
  weight: ['400'],
  variable: '--font-faculty-glyphic',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poltawskiNowy.variable} ${facultyGlyphic.variable} antialiased`}>
        <SessionClientProvider>
          <ProtectedPages>{children}</ProtectedPages>
        </SessionClientProvider>
      </body>
    </html>
  );
}
